export const APP_TOOLBAR_HEIGHT = 64;

export const BREADCRUMBS_HEIGHT = 24;

export const PAGE_TITLE_HEIGHT = 42;

export const APP_WITH_BREADCRUMBS_AND_TITLE_HEIGHT =
  APP_TOOLBAR_HEIGHT + BREADCRUMBS_HEIGHT + PAGE_TITLE_HEIGHT;
