name: Publish

on:
  push:
    branches:
      - main
      - beta

jobs:
  publish:
    permissions:
      id-token: write
      deployments: write
      contents: write

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
          echo "VERSION=$(npx semantic-release --dry-run | grep 'Published release' | sed 's/.*release //;s/ on.*//')" >> $GITHUB_ENV

      - name: Install and build
        run: |
          npm run postinstall
          npm run build

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
        run: |
          echo "VERSION=${{ env.VERSION }}"
          npm exec electron-builder -- --publish always --win --linux -c.extraMetadata.version=${{ env.VERSION }}
