name: Publish

on:
  push:
    branches:
      - main
      - beta
    paths:
      - 'app/**'
      - '.github/workflows/publish.yml'

jobs:
  publish:
    # Skip running release workflow on main if the commit is a release commit from beta
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}

    permissions:
      id-token: write
      deployments: write
      contents: write

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install and build
        working-directory: app
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Get next version
        working-directory: app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --dry-run
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create draft release
        env:
          VERSION: ${{ env.VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $VERSION --draft

      - name: Build and add assets to draft release
        working-directory: app
        env:
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
        run: |
          echo "VERSION: ${{ env.VERSION }}"
          npm exec electron-builder -- --publish onTagOrDraft -mwl -c.extraMetadata.version=$VERSION

      - name: Run semantic-release
        working-directory: app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
      # TODO: if this new pipeline flow works, we can remove draft from semantic-release and this will release
      - name: Publish Draft Release
        env:
          VERSION: ${{ env.VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the ID of the latest draft release
          DRAFT_RELEASE_TAG=$(gh release list --limit 1 --json tagName,isDraft,name --jq '.[] | select(.isDraft == true) | select(.tagName == "'$VERSION'") | .tagName')
          if [ -n "$DRAFT_RELEASE_TAG" ]; then
            gh release edit $DRAFT_RELEASE_TAG --draft=false --tag $DRAFT_RELEASE_TAG
          else
            echo "No draft release found"
            exit 1
          fi

      - name: Merge main into beta
        if: github.ref == 'refs/heads/main' # Only run this step when on main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin beta:beta
          git checkout beta
          git merge --no-ff origin/main -m "chore: merge main into beta after release [skip ci]"
          git push origin beta
