name: Test

on:
  pull_request:
    branches:
      - main
      - beta
    paths:
      - 'app/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: npm install
        working-directory: app
        run: |
          npm install

      - name: npm test
        working-directory: app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run package
          npm run lint
          npm exec tsc
          npm test
